//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademicLoadModule.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademicLoadModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учебная нагрузка:.
        /// </summary>
        public static string AcademicLoad {
            get {
                return ResourceManager.GetString("AcademicLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность:.
        /// </summary>
        public static string AcademicTitle {
            get {
                return ResourceManager.GetString("AcademicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить учебную группу.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление учебной группы.
        /// </summary>
        public static string AddingGroup {
            get {
                return ResourceManager.GetString("AddingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление преподавателя.
        /// </summary>
        public static string AddingTeacher {
            get {
                return ResourceManager.GetString("AddingTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить фотографию.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить преподавателя.
        /// </summary>
        public static string AddTeacher {
            get {
                return ResourceManager.GetString("AddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения:.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчетные листы кафедральной нагрузки.
        /// </summary>
        public static string CalculationSheets {
            get {
                return ResourceManager.GetString("CalculationSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расчетный листы кафедральной нагрузки отсутсвует, выберите файл в формате Excel..
        /// </summary>
        public static string CalculationSheetsEmpty {
            get {
                return ResourceManager.GetString("CalculationSheetsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить учебную группу.
        /// </summary>
        public static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить преподавателя.
        /// </summary>
        public static string DeleteTeacher {
            get {
                return ResourceManager.GetString("DeleteTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать учебную группу.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название группы:.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о учебных группах отсутсвует. Добавьте ифнормацию о новой учебной группе..
        /// </summary>
        public static string GroupsEmpty {
            get {
                return ResourceManager.GetString("GroupsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Почасовой фонд.
        /// </summary>
        public static string HourlyFond {
            get {
                return ResourceManager.GetString("HourlyFond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия:.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лекционная нагрузка:.
        /// </summary>
        public static string LectionLoad {
            get {
                return ResourceManager.GetString("LectionLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные о данной учебной группе будут удалены.
        /// </summary>
        public static string MessageDeleteGroup {
            get {
                return ResourceManager.GetString("MessageDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные о данном преподавателе будут удалены.
        /// </summary>
        public static string MessageDeleteTeacher {
            get {
                return ResourceManager.GetString("MessageDeleteTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество:.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нормы времени.
        /// </summary>
        public static string NormsTime {
            get {
                return ResourceManager.GetString("NormsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение..
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ставка:.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск по названию группы:.
        /// </summary>
        public static string SearchForGroup {
            get {
                return ResourceManager.GetString("SearchForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поис по ФИО:.
        /// </summary>
        public static string SearchForTeacher {
            get {
                return ResourceManager.GetString("SearchForTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать файл.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество студентов:.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество человек:.
        /// </summary>
        public static string StudentsNumber {
            get {
                return ResourceManager.GetString("StudentsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учебные группы.
        /// </summary>
        public static string StudyGroups {
            get {
                return ResourceManager.GetString("StudyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учебная группа успешно добавлена..
        /// </summary>
        public static string SuccessAddGroup {
            get {
                return ResourceManager.GetString("SuccessAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преподаватель успешно добавлен..
        /// </summary>
        public static string SuccessAddTeacher {
            get {
                return ResourceManager.GetString("SuccessAddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа успешно удалена..
        /// </summary>
        public static string SuccessDeleteGroup {
            get {
                return ResourceManager.GetString("SuccessDeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преподаватель успешно удален..
        /// </summary>
        public static string SuccessDeleteTeacher {
            get {
                return ResourceManager.GetString("SuccessDeleteTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преподаватели.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о преподавателях отсутсвует. Добавьте ифнормацию о новом преподавателе..
        /// </summary>
        public static string TeachersEmpty {
            get {
                return ResourceManager.GetString("TeachersEmpty", resourceCulture);
            }
        }
    }
}
